language: php

php:
  - 8.0
  - nightly

env:
    - IDS_FILTER_TYPE=json IDS_FILTER_SET=lib/IDS/default_filter.json
    - IDS_FILTER_TYPE=xml  IDS_FILTER_SET=lib/IDS/default_filter.xml

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev

notifications:
  email:
    - beahub@emscherland.de
